### ISSUE TITLE
Flows fail when using a non-advertised auth scope

### ISSUE THREAD

**Issue by DavidKelly-Praedictus** [globus/globus-automate-client#168]
Flows fail when using a non-advertised auth scope. The error is "For RunAs value User, unable to get tokens for scopes". Below are the steps to reproduce. 

1. Create an app on developers.globus.org ![Screenshot from 2022-07-08 08-52-38](https://user-images.githubusercontent.com/1781986/178022444-7efb4023-604e-4bae-993b-23b1eef84150.png)
2. Create an auth scope definition ![Screenshot from 2022-07-08 09-03-35](https://user-images.githubusercontent.com/1781986/178022555-d250f78e-66b4-4c0f-b62d-64fbae4463ca.png)
3. Create the scope ![Screenshot from 2022-07-08 09-03-55](https://user-images.githubusercontent.com/1781986/178022709-760a40ea-782c-47b1-b66d-1bd41a174b57.png)
4. Add the new scope and client id/secret to the action provider code
5. Running a single action using the new action provider will work  ![Screenshot from 2022-07-08 09-23-53](https://user-images.githubusercontent.com/1781986/178023113-7077a513-25d5-42d0-b2b3-56feffd98888.png) ![Screenshot from 2022-07-08 09-36-53](https://user-images.githubusercontent.com/1781986/178023009-aafbf96c-f759-4c90-817c-7ea65126488a.png)
6. Create a flow that uses the action ![Screenshot from 2022-07-08 09-43-35](https://user-images.githubusercontent.com/1781986/178024667-5ce10827-996a-4bf4-a115-50bc27e133f8.png)
7. Deploy the flow  ![Screenshot from 2022-07-08 09-41-44](https://user-images.githubusercontent.com/1781986/178023768-e6123e67-6406-4bab-a14d-825ff0bf1b75.png) ![Screenshot from 2022-07-08 09-42-56](https://user-images.githubusercontent.com/1781986/178026620-bfae9042-6982-44ca-8b18-664704ece3c6.png)
8. Run the flow. This will trigger the error and prevent it from running ![Screenshot from 2022-07-08 09-44-58](https://user-images.githubusercontent.com/1781986/178024303-b8a53e14-cc6a-4023-aa37-ec421b06e84b.png) ![Screenshot from 2022-07-08 09-46-20](https://user-images.githubusercontent.com/1781986/178024108-d712a216-2e14-460b-94c5-1abba5fd1a00.png)

**Comment by kurtmckee** [comment]
I've migrated this to an internal issue tracker. Thanks for reporting this, David!
